{{- if .Values.api.podDisruptionBudget.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "code-story.fullname" . }}-api
  labels:
    {{- include "code-story.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
spec:
  minAvailable: {{ .Values.api.podDisruptionBudget.minAvailable }}
  selector:
    matchLabels:
      {{- include "code-story.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: api
{{- end }}
