{{- if .Values.web.podDisruptionBudget.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "code-story.fullname" . }}-web
  labels:
    {{- include "code-story.labels" . | nindent 4 }}
    app.kubernetes.io/component: web
spec:
  minAvailable: {{ .Values.web.podDisruptionBudget.minAvailable }}
  selector:
    matchLabels:
      {{- include "code-story.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: web
{{- end }}
